---
- name: Deploy Nginx with Docker
  hosts: demo
  become: yes
  tasks:
    - name: Установить пакеты для работы с apt-репозиториями
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common

    - name: Добавить GPG ключ Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавить Docker репозиторий
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Установить Docker
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Убедиться, что служба Docker запущена и включена при загрузке
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    - name: Создать директорию для конфигурационного файла Nginx
      ansible.builtin.file:
        path: /opt/nginx_conf
        state: directory

    - name: Разместить конфигурационный файл Nginx
      ansible.builtin.copy:
        src: nginx.conf
        dest: /opt/nginx_conf/nginx.conf
        mode: '0644'

    - name: Запустить контейнер Nginx с Docker
      ansible.builtin.docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        pull: yes
        ports:
          - "8080:80"
        volumes:
          - "/opt/nginx_conf/nginx.conf:/etc/nginx/nginx.conf"

